# Generated by Django 3.0.6 on 2020-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
