# Generated by Django 3.0.6 on 2020-05-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
