# Generated by Django 3.0.6 on 2020-05-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_crawler'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler', to='inventory.Crawler'),
        ),
        migrations.DeleteModel(
            name='Crawler',
        ),
    ]
