# Generated by Django 3.0.6 on 2020-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20200527_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingrecord',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
