# Generated by Django 3.0.6 on 2020-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20200527_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingrecord',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
