# Generated by Django 3.0.6 on 2020-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_crawlingrecord_is_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingrecord',
            name='complete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='crawlingrecord',
            name='file_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
